import {
	getCarrierOrders,
	getCarrierCurrentDeliveries,
	getCarrierPendingDeliveries,
	getCarrierDeliveredDeliveries,
} from './Carriers';
import { getCustomerOrders, getCustomerCurrentDeliveries } from './Customers';
import {
	createOrder,
	getOrderByID,
	getOrdersRestaurant,
	updateOrder,
	confirmOrder,
	deleteInstance,
	markAsMade,
	markAsDelivered,
} from './Orders';

import {
	registerInstance,
	getRestaurantInstances,
	getRestaurantOrders,
	updateInstance,
	getAllRestaurants,
	addFoodToRestaurant,
	getFoodFromMenu,
	updateRestaurantsFood,
	deleteRestaurantsFood,
	getInstancePendingOrders,
	updateRestaurant,
	getAvailableFoodTypes,
	rateRestaurant,
	searchRestaurant,
	getReviews,
	getInstanceCurrentOrders,
} from './Restaurants';
import {
	loginAsUser,
	registerUser,
	deleteCurrentUser,
	updateCurrentUser,
	getUserByUsername,
	getUserById,
	getMessageHistoryWithUser,
} from './Users';

export {
	loginAsUser,
	updateCurrentUser,
	registerUser,
	deleteCurrentUser,
	registerInstance,
	getRestaurantInstances,
	updateRestaurant,
	updateInstance,
	createOrder,
	getOrderByID,
	getOrdersRestaurant,
	rateRestaurant,
	getAvailableFoodTypes,
	getReviews,
	updateOrder,
	confirmOrder,
	deleteInstance,
	getAllRestaurants,
	getRestaurantOrders,
	addFoodToRestaurant,
	getFoodFromMenu,
	updateRestaurantsFood,
	deleteRestaurantsFood,
	markAsMade,
	getCarrierOrders,
	getCustomerOrders,
	getCarrierCurrentDeliveries,
	getCarrierPendingDeliveries,
	getCarrierDeliveredDeliveries,
	getInstancePendingOrders,
	markAsDelivered,
	getCustomerCurrentDeliveries,
	getInstanceCurrentOrders,
	getUserByUsername,
	getUserById,
	getMessageHistoryWithUser,
};
