import {
	createOrder,
	getOrderByID,
	getOrdersRestaurant,
	updateOrder,
	confirmOrder,
	deleteInstance,
	addFoodToOrder,
	deleteFoodFromOrder,
	getFoodFromOrder,
	getPendingOrder,
	deleteFoodRelationFromOrder,
	markAsDelivered,
	markAsMade,
} from './order';

export {
	createOrder,
	getOrderByID,
	getOrdersRestaurant,
	updateOrder,
	confirmOrder,
	deleteInstance,
	addFoodToOrder,
	deleteFoodFromOrder,
	getFoodFromOrder,
	getPendingOrder,
	deleteFoodRelationFromOrder,
	markAsDelivered,
	markAsMade,
};
